export const LOAD_VIDEOS = "LOAD_VIDEOS";
export const LOAD_VIDEOS_SUCCESS = "LOAD_VIDEOS_SUCCESS";

export const LOAD_VIDEOS_FAILURE = "LOAD_VIDEOS_FAILURE";

export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const SELECT_MOVIE = "SELECT_MOVIE";
export const SELECT_OVERVIEW = "SELECT_OVERVIEW";
export const SELECT_ACTION = "SELECT_ACTION";
